---
title: About Us
---

## Sean Lopp
Sean grew up in Conifer, CO. He graduated from Mines in May 2015 with a B.S. in Statistics. He currently works remotely as a software salesman at RStudio. In his free time he skis, bikes, and recently began kayaking with Madison's help!


## Madi Kellar
Madison grew up in Federal Way, WA. She graduated from Colorado School of Mines in May 2016 with a B.S. in Applied Math. She is on her way to becoming a high school math teacher through the Boettcher Teacher Residency. She is currently in school for her Masters in Education and student teaches in Thornton, CO. With Sean's help she has become a much better skier.

## Lopp Family
Sean's parents are Roger and Maureen. Both grew up in small towns in Indiana, met at Purdue University, and have been married for 30 years. After vacationing in Colorado, they made Evergreen their home in the early 90s. Sean was born in 1994, and Colleen followed in 1996. Roger and Maureen both have technology related jobs and spend time off enjoying the mountains.  Colleen is working on a Biology degree at Regis University.  In addition to juggling jobs, she does volunteer work and has an active social life.



## Kellar Family
Jeff and Diane are both from Minnesota, don't-cha-know.  They met in high school.  Jeff moved to Washington to work as an engineer for the Boeing Company after graduating from North Dakota State University.  They had a December wedding in Fargo, ND, so Madison is continuing the cold and snowy wedding tradition. Afterwards, Diane moved to Washington and completed her BS at University of Washington and also went to work for The Boeing Company.  They have lived in Federal Way, WA ever since (that's just south of Seattle). After most people had given up on them ever having children, Alyssa was born.  She was so much fun Jeff and Diane decided to have another and in 1994 Madison was born.  Both girls are the joy of their life!  Jeff continues to work for the Boeing Company.  Diane went back to school for her Master's in Business Administration and continued to work for Boeing until 1997 when she decided to stay home and play with the girls.  Today she is an obsessed quilter.  Jeff loves to sail, make things on his lathe and make beer in his spare time.  Alyssa also resides in Washington and is a music teacher. They miss Madison and constantly beg her to visit and so they buy a lot of plane tickets. Jeff and Diane hope to buy an RV and retire soon, spending time in both Washington and Colorado to see their girls.  They are thrilled Madison has found a nice Catholic boy! 
