---
output:
  html_document:
    toc: true
    toc_float: true
---



### Contact
For any questions contact Madison Kellar at madi.kellar@gmail.com. On the day of the wedding, please reach out to .


### Where is the wedding?
The wedding will be taking place at [Our Lady of Peace](http://www.summitcatholic.org/our-lady-of-peace-silverthorne/).

<iframe width="800" height="500" src="http://www.summitcatholic.org/our-lady-of-peace-silverthorne/"  frameborder="0"  allowfullscreen></iframe>

### When is the wedding?
The wedding is Saturday January 7th, 2017. The ceremony begins at 2:00 pm, please plan on arriving a half hour early. It takes about an hour to get to Silverthorne from Denver but check [CDOT](http://www.cotrip.org/highways.htm#?commuteRouteId=54) for traffic and weather.

### A Catholic wedding?

A Catholic wedding is about an hour and a half long, and includes a mass with Holy Communion.

Communion?

For Catholics:
As Catholics, we fully participate in the celebration of the Eucharist when we receive Holy Communion. We are encouraged to recieve Holy Communion devoutly and frequently. In order to be properly disposed to receive Communion, participants should not be conscious of grave sin and normally should have fasted for one hour. A frequent reception of the Sacrament of Penance is encouraged for all who are receiving Communion.

For Fellow Christians:
We welcome our fellow Christians to this celebration of the Eucharist as our brothers and sisters. We pray that our commmon baptism and the action of the Holy Spirit in this Eucharist will draw us closer to one another and begin to dispel the sad divisions which separate us. Because Catholics believe that the celebration is the Body and Blood of Christ, members of those churches with whom we are not yet fully united are ordinarily not admitted to Holy Communion.

For Non-Christians:
We also welcome to this celebration those who do not share our faith in Jesus Christ. While we cannot admit them to Holy Communion, we are so glad you have come to join us.

For those not recieving Holy Communion, you may remain in your seat during Holy Communion, or come forward with your arms crossed over your chest to receive a blessing.


### Where is the wedding reception?
The wedding reception will be at Warren Station at Keystone.
164 Ida Belle Dr.
Keystone, CO 80435

### When is the reception?
The reception begins at 4:30pm and ends at 8:30pm.

### How do I get from the wedding to the reception?



### Where is lodging for out-of-town guests?

### How do I get from the airport to the hotel in Silverthorne?


### How do I RSVP?
Go to the RSVP [site](http://seandemo.shinyapps.io/elopped), or send us the RSVP card that came with your invitiation.

### How do I change my RSVP?
Contact Madison (madi.kellar@gmail.com) or Sean.
